name: Benchmark Prompts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install tiktoken

      - name: Run benchmark
        run: |
          python scripts/benchmark.py

      - name: Commit benchmark updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .benchmark/data.json README.md
          git diff --staged --quiet || git commit -m "Update benchmarks for $(cat .version) [skip ci]"
          git push