name: Benchmark Prompts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install tiktoken

      - name: Run benchmark
        run: |
          python scripts/benchmark.py

      - name: Create benchmark PR
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .benchmark/data.json README.md

          if git diff --staged --quiet; then
            echo "No benchmark changes"
            exit 0
          fi

          VERSION=$(cat .version)
          BRANCH="benchmarks/v${VERSION}"

          git checkout -b "$BRANCH"
          git commit -m "Update benchmarks for ${VERSION}"
          git push -u origin "$BRANCH"

          gh pr create \
            --title "Update benchmarks for ${VERSION}" \
            --body "Automated benchmark update for version ${VERSION}" \
            --base main \
            --head "$BRANCH"
        env:
          GH_TOKEN: ${{ github.token }}