name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate bash syntax in markdown
        run: ./tests/validate-syntax.sh

      - name: Validate markdown cross-references
        run: ./tests/validate-md-refs.sh
